# Generated by Django 3.2.2 on 2025-03-26 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, verbose_name='index')),
                ('id', models.IntegerField(verbose_name='id')),
                ('thumbnail', models.TextField(verbose_name='thumbnail')),
                ('image', models.TextField(verbose_name='image')),
                ('primary', models.TextField(verbose_name='primary')),
            ],
            options={
                'verbose_name': 'boardgame',
                'verbose_name_plural': 'boardgames',
                'db_table': 'bg_list',
                'ordering': ('index',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boardgame_detail',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, verbose_name='index')),
                ('id', models.IntegerField(verbose_name='id')),
                ('thumbnail', models.TextField(default='', verbose_name='thumbnail')),
                ('image', models.TextField(verbose_name='image')),
                ('primary', models.TextField(verbose_name='primary')),
                ('description', models.TextField(verbose_name='description')),
                ('minplayers', models.IntegerField()),
                ('maxplayers', models.IntegerField()),
                ('playingtime', models.IntegerField()),
                ('board_game_rank', models.IntegerField(default='')),
                ('boardgamecategory', models.TextField()),
                ('average', models.FloatField()),
                ('alternate', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'boardgame_detail',
                'verbose_name_plural': 'boardgame_details',
                'db_table': 'bg_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('rated_at', models.DateTimeField(auto_now=True)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.boardgame_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'list_rating',
                'managed': True,
                'unique_together': {('user', 'boardgame')},
            },
        ),
    ]
