# Generated by Django 3.2.2 on 2024-07-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_post_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('index', models.IntegerField(verbose_name='index')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('thumbnail', models.TextField(verbose_name='thumbnail')),
                ('image', models.TextField(verbose_name='image')),
                ('primary', models.TextField(verbose_name='primary')),
            ],
            options={
                'verbose_name': 'boardgame',
                'verbose_name_plural': 'boardgames',
                'db_table': 'bg_list',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Boardgame_detail',
            fields=[
                ('index', models.IntegerField(verbose_name='index')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('image', models.TextField(verbose_name='image')),
                ('primary', models.TextField(verbose_name='primary')),
                ('description', models.TextField(verbose_name='description')),
                ('minplayers', models.IntegerField()),
                ('maxplayers', models.IntegerField()),
                ('playingtime', models.IntegerField()),
                ('Board_Game_Rank', models.IntegerField(verbose_name='Board Game Rank')),
                ('boardgamecategory', models.TextField()),
                ('average', models.FloatField()),
            ],
            options={
                'verbose_name': 'boardgame_detail',
                'verbose_name_plural': 'boardgame_details',
                'db_table': 'bg_info',
                'ordering': ('index',),
            },
        ),
    ]
